# Generated by Django 5.1.1 on 2024-09-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_inovicetable_created_inovicetable_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttable',
            name='urgency_status',
            field=models.CharField(default='in_review', max_length=100),
        ),
    ]
