# Generated by Django 5.1.1 on 2024-10-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_requesttable_urgency_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inoviceTable',
            new_name='invoiceTable',
        ),
        migrations.AddField(
            model_name='requesttable',
            name='iid',
            field=models.CharField(default='random', max_length=100),
        ),
    ]
