# Generated by Django 5.1.1 on 2024-10-04 05:29

import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_inovicetable_invoicetable_requesttable_iid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='request_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('accepted', 'Accepted'), ('checked', 'Checked'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('rejected', 'Rejected')], max_length=15),
        ),
        migrations.CreateModel(
            name='requestNotificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('notification_by', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=250)),
                ('message_type', models.CharField(choices=[('success', 'success'), ('warning', 'warning'), ('danger', 'danger')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.requesttable')),
            ],
        ),
    ]
