# Generated by Django 5.1.1 on 2024-10-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_requesttable_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestnotificationtable',
            name='user',
            field=models.CharField(default='Email', max_length=30),
        ),
    ]
