# Generated by Django 5.1.1 on 2024-09-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('salesman', 'Salesman'), ('receiver', 'Receiver'), ('checker', 'Checker'), ('accountant', 'Accountant')], max_length=30),
        ),
    ]
