# Generated by Django 5.1.1 on 2024-10-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('salesman', 'Salesman'), ('receiver', 'Receiver'), ('checker', 'Checker'), ('accountant', 'Accountant'), ('admin', 'Admin')], max_length=30),
        ),
    ]
